IF NOT EXISTS (SELECT name FROM master.sys.databases where name = 'ODataAPIDatabase')

	IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
	begin
	EXEC [ODataAPIDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
	end
	GO
	ALTER DATABASE [ODataAPIDatabase] SET ANSI_NULL_DEFAULT OFF
	GO
	ALTER DATABASE [ODataAPIDatabase] SET ANSI_NULLS OFF
	GO
	ALTER DATABASE [ODataAPIDatabase] SET ANSI_PADDING OFF
	GO
	ALTER DATABASE [ODataAPIDatabase] SET ANSI_WARNINGS OFF
	GO
	ALTER DATABASE [ODataAPIDatabase] SET ARITHABORT OFF
	GO
	ALTER DATABASE [ODataAPIDatabase] SET AUTO_CLOSE ON
	GO
	ALTER DATABASE [ODataAPIDatabase] SET AUTO_SHRINK OFF
	GO
	ALTER DATABASE [ODataAPIDatabase] SET AUTO_UPDATE_STATISTICS ON
	GO
	ALTER DATABASE [ODataAPIDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF
	GO
	ALTER DATABASE [ODataAPIDatabase] SET CURSOR_DEFAULT  GLOBAL
	GO
	ALTER DATABASE [ODataAPIDatabase] SET CONCAT_NULL_YIELDS_NULL OFF
	GO
	ALTER DATABASE [ODataAPIDatabase] SET NUMERIC_ROUNDABORT OFF
	GO
	ALTER DATABASE [ODataAPIDatabase] SET QUOTED_IDENTIFIER OFF
	GO
	ALTER DATABASE [ODataAPIDatabase] SET RECURSIVE_TRIGGERS OFF
	GO
	ALTER DATABASE [ODataAPIDatabase] SET  ENABLE_BROKER
	GO
	ALTER DATABASE [ODataAPIDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
	GO
	ALTER DATABASE [ODataAPIDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF
	GO
	ALTER DATABASE [ODataAPIDatabase] SET TRUSTWORTHY OFF
	GO
	ALTER DATABASE [ODataAPIDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF
	GO
	ALTER DATABASE [ODataAPIDatabase] SET PARAMETERIZATION SIMPLE
	GO
	ALTER DATABASE [ODataAPIDatabase] SET READ_COMMITTED_SNAPSHOT ON
	GO
	ALTER DATABASE [ODataAPIDatabase] SET HONOR_BROKER_PRIORITY OFF
	GO
	ALTER DATABASE [ODataAPIDatabase] SET RECOVERY FULL
	GO
	ALTER DATABASE [ODataAPIDatabase] SET  MULTI_USER
	GO
	ALTER DATABASE [ODataAPIDatabase] SET PAGE_VERIFY CHECKSUM
	GO
	ALTER DATABASE [ODataAPIDatabase] SET DB_CHAINING OFF
	GO
	ALTER DATABASE [ODataAPIDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
	GO
	ALTER DATABASE [ODataAPIDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS
	GO
	ALTER DATABASE [ODataAPIDatabase] SET DELAYED_DURABILITY = DISABLED
	GO
	ALTER DATABASE [ODataAPIDatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF
	GO
	ALTER DATABASE [ODataAPIDatabase] SET QUERY_STORE = OFF
	GO
	ALTER DATABASE [ODataAPIDatabase] SET  READ_WRITE
	GO
	USE [ODataAPIDatabase]
	GO
	/****** Object:  Table [dbo].[GujaratDistricts]    Script Date: 03-07-2023 18:48:17 ******/
	SET ANSI_NULLS ON
	GO
	SET QUOTED_IDENTIFIER ON
	GO

	CREATE TABLE [dbo].[GujaratDistricts](
		[ID] [uniqueidentifier] NOT NULL,
		[STCode] [int] NOT NULL,
		[StateName] [nvarchar](100) NOT NULL,
		[DTCode] [int] NOT NULL,
		[DistrictName] [nvarchar](100) NOT NULL,
		[SDTCode] [int] NOT NULL,
		[SubDistrictName] [nvarchar](100) NOT NULL,
		[TownCode] [int] NOT NULL,
		[AreaName] [nvarchar](100) NOT NULL,
	CONSTRAINT [PK_GujaratDistricts] PRIMARY KEY CLUSTERED
	(
		[ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]
	GO
	ALTER TABLE [dbo].[GujaratDistricts] ADD  DEFAULT (newsequentialid()) FOR [ID]
	GO


	CREATE VIEW [dbo].[VW_database]
	AS
	SELECT [STCode],[StateName],[DTCode],[DistrictName],[SDTCode],[SubDistrictName],[TownCode],[AreaName]
	FROM [dbo].[GujaratDistricts];
	GO

	BULK INSERT [dbo].[VW_database]
	FROM '/app/script/data.csv'
	WITH (FORMAT = 'CSV'
		, FIRSTROW=2
		, FIELDTERMINATOR = ','
		, ROWTERMINATOR = '0x0a',KEEPIDENTITY);
	GO
GO