apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-script
data:
  entrypoint.sh: |
      #!/bin/bash
      /opt/mssql/bin/sqlservr &
      /opt/mssql-tools/bin/sqlcmd -S mssql-service,1433 -U sa -P Password1234 -Q "CREATE DATABASE ODataAPIDatabase" -d master 
      /opt/mssql-tools/bin/sqlcmd -S mssql-service,1433 -U sa -P Password1234 -d ODataAPIDatabase -i /app/script/script.sql 
      tail -f /dev/null

  script.sql: |
    IF NOT EXISTS (SELECT name FROM master.sys.databases where name = 'ODataAPIDatabase')
      IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
      begin
      EXEC [ODataAPIDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
      end
      GO
      ALTER DATABASE [ODataAPIDatabase] SET ANSI_NULL_DEFAULT OFF
      GO
      ALTER DATABASE [ODataAPIDatabase] SET ANSI_NULLS OFF
      GO
      ALTER DATABASE [ODataAPIDatabase] SET ANSI_PADDING OFF
      GO
      ALTER DATABASE [ODataAPIDatabase] SET ANSI_WARNINGS OFF
      GO
      ALTER DATABASE [ODataAPIDatabase] SET ARITHABORT OFF
      GO
      ALTER DATABASE [ODataAPIDatabase] SET AUTO_CLOSE ON
      GO
      ALTER DATABASE [ODataAPIDatabase] SET AUTO_SHRINK OFF
      GO
      ALTER DATABASE [ODataAPIDatabase] SET AUTO_UPDATE_STATISTICS ON
      GO
      ALTER DATABASE [ODataAPIDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF
      GO
      ALTER DATABASE [ODataAPIDatabase] SET CURSOR_DEFAULT  GLOBAL
      GO
      ALTER DATABASE [ODataAPIDatabase] SET CONCAT_NULL_YIELDS_NULL OFF
      GO
      ALTER DATABASE [ODataAPIDatabase] SET NUMERIC_ROUNDABORT OFF
      GO
      ALTER DATABASE [ODataAPIDatabase] SET QUOTED_IDENTIFIER OFF
      GO
      ALTER DATABASE [ODataAPIDatabase] SET RECURSIVE_TRIGGERS OFF
      GO
      ALTER DATABASE [ODataAPIDatabase] SET  ENABLE_BROKER
      GO
      ALTER DATABASE [ODataAPIDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
      GO
      ALTER DATABASE [ODataAPIDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF
      GO
      ALTER DATABASE [ODataAPIDatabase] SET TRUSTWORTHY OFF
      GO
      ALTER DATABASE [ODataAPIDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF
      GO
      ALTER DATABASE [ODataAPIDatabase] SET PARAMETERIZATION SIMPLE
      GO
      ALTER DATABASE [ODataAPIDatabase] SET READ_COMMITTED_SNAPSHOT ON
      GO
      ALTER DATABASE [ODataAPIDatabase] SET HONOR_BROKER_PRIORITY OFF
      GO
      ALTER DATABASE [ODataAPIDatabase] SET RECOVERY FULL
      GO
      ALTER DATABASE [ODataAPIDatabase] SET  MULTI_USER
      GO
      ALTER DATABASE [ODataAPIDatabase] SET PAGE_VERIFY CHECKSUM
      GO
      ALTER DATABASE [ODataAPIDatabase] SET DB_CHAINING OFF
      GO
      ALTER DATABASE [ODataAPIDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
      GO
      ALTER DATABASE [ODataAPIDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS
      GO
      ALTER DATABASE [ODataAPIDatabase] SET DELAYED_DURABILITY = DISABLED
      GO
      ALTER DATABASE [ODataAPIDatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF
      GO
      ALTER DATABASE [ODataAPIDatabase] SET QUERY_STORE = OFF
      GO
      ALTER DATABASE [ODataAPIDatabase] SET  READ_WRITE
      GO
      USE [ODataAPIDatabase]
      GO
      /****** Object:  Table [dbo].[GujaratDistricts]    Script Date: 03-07-2023 18:48:17 ******/
      SET ANSI_NULLS ON
      GO
      SET QUOTED_IDENTIFIER ON
      GO

      CREATE TABLE [dbo].[GujaratDistricts](
        [ID] [uniqueidentifier] NOT NULL,
        [STCode] [int] NOT NULL,
        [StateName] [nvarchar](100) NOT NULL,
        [DTCode] [int] NOT NULL,
        [DistrictName] [nvarchar](100) NOT NULL,
        [SDTCode] [int] NOT NULL,
        [SubDistrictName] [nvarchar](100) NOT NULL,
        [TownCode] [int] NOT NULL,
        [AreaName] [nvarchar](100) NOT NULL,
      CONSTRAINT [PK_GujaratDistricts] PRIMARY KEY CLUSTERED
      (
        [ID] ASC
      )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
      ) ON [PRIMARY]
      GO
      ALTER TABLE [dbo].[GujaratDistricts] ADD  DEFAULT (newsequentialid()) FOR [ID]
      GO


      CREATE VIEW [dbo].[VW_database]
      AS
      SELECT [STCode],[StateName],[DTCode],[DistrictName],[SDTCode],[SubDistrictName],[TownCode],[AreaName]
      FROM [dbo].[GujaratDistricts];
      GO

      BULK INSERT [dbo].[VW_database]
      FROM '/app/script/data.csv'
      WITH (FORMAT = 'CSV'
        , FIRSTROW=2
        , FIELDTERMINATOR = ','
        , ROWTERMINATOR = '0x0a',KEEPIDENTITY);
      GO
    GO
  data.csv: |
    STCode,StateName,DTCode,DistrictName,SDTCode,SubDistrictName,TownCode,AreaName
    24,GUJARAT,468,Kachchh,3723,Rapar,802442,Rapar (M)
    24,GUJARAT,468,Kachchh,3724,Bhachau,802443,Bhachau (M)
    24,GUJARAT,468,Kachchh,3725,Anjar,802444,Anjar (M)
    24,GUJARAT,468,Kachchh,3726,Bhuj,802445,Bhuj (M + OG)
    24,GUJARAT,468,Kachchh,3726,Bhuj,802445,Bhuj (M)
    24,GUJARAT,468,Kachchh,3729,Mandvi,802446,Mandvi (M)
    24,GUJARAT,468,Kachchh,3731,Gandhidham,802447,Gandhidham (M)
    24,GUJARAT,469,Banas Kantha,3733,Tharad,802448,Tharad (M)
    24,GUJARAT,469,Banas Kantha,3734,Dhanera,802449,Dhanera (M)
    24,GUJARAT,469,Banas Kantha,3739,Palanpur,802450,Palanpur (M + OG)
    24,GUJARAT,469,Banas Kantha,3739,Palanpur,802450,Palanpur (M)
    24,GUJARAT,469,Banas Kantha,3740,Deesa,802451,Deesa (M)
    24,GUJARAT,469,Banas Kantha,3742,Bhabhar,802452,Bhabhar (M)
    24,GUJARAT,469,Banas Kantha,3743,Kankrej,802453,Thara (M)
    24,GUJARAT,470,Patan  ,3745,Radhanpur,802454,Radhanpur (M)
    24,GUJARAT,470,Patan  ,3746,Sidhpur,802455,Sidhpur (M + OG)
    24,GUJARAT,470,Patan  ,3746,Sidhpur,802455,Sidhpur (M)
    24,GUJARAT,470,Patan  ,3747,Patan,802456,Patan (M + OG)
    24,GUJARAT,470,Patan  ,3747,Patan,802456,Patan (M)
    24,GUJARAT,470,Patan  ,3748,Harij,802457,Harij (M)
    24,GUJARAT,470,Patan  ,3750,Chanasma,802458,Chanasma (M)
    24,GUJARAT,471,Mahesana,3752,Kheralu,802459,Kheralu (M)
    24,GUJARAT,471,Mahesana,3753,Unjha,802460,Unjha (M)
    24,GUJARAT,471,Mahesana,3754,Visnagar,802461,Visnagar (M + OG)
    24,GUJARAT,471,Mahesana,3754,Visnagar,802461,Visnagar (M)
    24,GUJARAT,471,Mahesana,3755,Vadnagar,802462,Vadnagar (M)
    24,GUJARAT,471,Mahesana,3756,Vijapur,802463,Vijapur (M + OG)
    24,GUJARAT,471,Mahesana,3756,Vijapur,802463,Vijapur (M)
    24,GUJARAT,471,Mahesana,3757,Mahesana,802464,Mahesana (M + OG)
    24,GUJARAT,471,Mahesana,3757,Mahesana,802464,Mahesana (M)
    24,GUJARAT,471,Mahesana,3759,Kadi,802465,Kadi (M + OG)
    24,GUJARAT,471,Mahesana,3759,Kadi,802465,Kadi (M)
    24,GUJARAT,472,Sabar Kantha,3760,Khedbrahma,802466,Khedbrahma (M)
    24,GUJARAT,472,Sabar Kantha,3762,Vadali,802467,Vadali (M)
    24,GUJARAT,472,Sabar Kantha,3763,Idar,802468,Idar (M + OG)
    24,GUJARAT,472,Sabar Kantha,3763,Idar,802468,Idar (M)
    24,GUJARAT,472,Sabar Kantha,3766,Himatnagar,802469,Himatnagar (M)
    24,GUJARAT,472,Sabar Kantha,3767,Prantij,802470,Prantij (M)
    24,GUJARAT,472,Sabar Kantha,3768,Talod,802471,Talod (M)
    24,GUJARAT,472,Sabar Kantha,3769,Modasa,802472,Modasa (M)
    24,GUJARAT,472,Sabar Kantha,3772,Bayad,802473,Bayad (M)
    24,GUJARAT,473,Gandhinagar,3773,Kalol,802474,Chhatral INA (INA)
    24,GUJARAT,473,Gandhinagar,3773,Kalol,802475,Kalol (M + OG)
    24,GUJARAT,473,Gandhinagar,3773,Kalol,802475,Kalol (M)
    24,GUJARAT,473,Gandhinagar,3773,Kalol,802476,Kalol INA (INA)
    24,GUJARAT,473,Gandhinagar,3774,Mansa,802477,Mansa (M)
    24,GUJARAT,473,Gandhinagar,3775,Gandhinagar,802478,Pethapur (M)
    24,GUJARAT,473,Gandhinagar,3775,Gandhinagar,802479,Gandhinagar (NA + OG)
    24,GUJARAT,473,Gandhinagar,3775,Gandhinagar,802479,Gandhinagar (NA)
    24,GUJARAT,473,Gandhinagar,3776,Dehgam,802480,Dehgam (M)
    24,GUJARAT,474,Ahmadabad,3779,Viramgam,802481,Viramgam (M)
    24,GUJARAT,474,Ahmadabad,3780,Sanand,802482,Sanand (M + OG)
    24,GUJARAT,474,Ahmadabad,3780,Sanand,802482,Sanand (M)
    24,GUJARAT,474,Ahmadabad,3781,Ahmadabad City,802483,Ahmadabad Cantonment (CB)
    24,GUJARAT,474,Ahmadabad,3781,Ahmadabad City,802484,Ahmadabad (M Corp. + OG) (Part)
    24,GUJARAT,474,Ahmadabad,3782,Daskroi,802484,Ahmadabad (M Corp. + OG) (Part)
    24,GUJARAT,474,Ahmadabad,3782,Daskroi,802485,Bareja (M)
    24,GUJARAT,474,Ahmadabad,3783,Dholka,802486,Dholka (M + OG)
    24,GUJARAT,474,Ahmadabad,3783,Dholka,802486,Dholka (M)
    24,GUJARAT,474,Ahmadabad,3784,Bavla,802487,Bavla (M + OG)
    24,GUJARAT,474,Ahmadabad,3784,Bavla,802487,Bavla (M)
    24,GUJARAT,474,Ahmadabad,3786,Barwala,802488,Barwala (M)
    24,GUJARAT,474,Ahmadabad,3787,Dhandhuka,802489,Dhandhuka (M)
    24,GUJARAT,475,Surendranagar,3788,Halvad,802490,Halvad (M)
    24,GUJARAT,475,Surendranagar,3789,Dhrangadhra,802491,Dhrangadhra (M)
    24,GUJARAT,475,Surendranagar,3790,Dasada,802492,Patdi (M)
    24,GUJARAT,475,Surendranagar,3792,Wadhwan,802493,Surendranagar Dudhrej (M)
    24,GUJARAT,475,Surendranagar,3792,Wadhwan,802494,Wadhwan (M)
    24,GUJARAT,475,Surendranagar,3794,Chotila,802495,Thangadh (M)
    24,GUJARAT,475,Surendranagar,3794,Chotila,802496,Chotila (M)
    24,GUJARAT,475,Surendranagar,3797,Limbdi,802497,Limbdi (M)
    24,GUJARAT,476,Rajkot,3798,Maliya,802498,Maliya (M)
    24,GUJARAT,476,Rajkot,3799,Morvi,802499,Morvi (M + OG)
    24,GUJARAT,476,Rajkot,3799,Morvi,802499,Morvi (M)
    24,GUJARAT,476,Rajkot,3801,Wankaner,802500,Wankaner (M)
    24,GUJARAT,476,Rajkot,3803,Rajkot,802501,Rajkot (M Corp. + OG)
    24,GUJARAT,476,Rajkot,3803,Rajkot,802501,Rajkot (M Corp.)
    24,GUJARAT,476,Rajkot,3804,Lodhika,802502,Lodhika (INA)
    24,GUJARAT,476,Rajkot,3806,Jasdan,802503,Jasdan (M)
    24,GUJARAT,476,Rajkot,3807,Gondal,802504,Gondal (M)
    24,GUJARAT,476,Rajkot,3809,Upleta,802505,Bhayavadar (M)
    24,GUJARAT,476,Rajkot,3809,Upleta,802506,Upleta (M)
    24,GUJARAT,476,Rajkot,3810,Dhoraji,802507,Dhoraji (M)
    24,GUJARAT,476,Rajkot,3811,Jetpur,802508,Jetpur Navagadh (M)
    24,GUJARAT,477,Jamnagar,3812,Okhamandal,802509,Okha (M)
    24,GUJARAT,477,Jamnagar,3812,Okhamandal,802510,Dwarka (M)
    24,GUJARAT,477,Jamnagar,3813,Khambhalia,802511,Salaya (M)
    24,GUJARAT,477,Jamnagar,3813,Khambhalia,802512,Khambhalia (M)
    24,GUJARAT,477,Jamnagar,3814,Jamnagar,802513,Sikka (M)
    24,GUJARAT,477,Jamnagar,3814,Jamnagar,802514,GSFC (Motikhavdi Sikka) (INA)
    24,GUJARAT,477,Jamnagar,3814,Jamnagar,802515,Reliance Complex (INA)
    24,GUJARAT,477,Jamnagar,3814,Jamnagar,802516,Jamnagar (M Corp. + OG)
    24,GUJARAT,477,Jamnagar,3814,Jamnagar,802516,Jamnagar (M Corp.)
    24,GUJARAT,477,Jamnagar,3816,Dhrol,802517,Dhrol (M)
    24,GUJARAT,477,Jamnagar,3817,Kalavad,802518,Kalavad (M)
    24,GUJARAT,477,Jamnagar,3819,Kalyanpur,802519,Raval (M)
    24,GUJARAT,477,Jamnagar,3820,Bhanvad,802520,Bhanvad (M)
    24,GUJARAT,477,Jamnagar,3821,Jamjodhpur,802521,Jamjodhpur (M)
    24,GUJARAT,478,Porbandar ,3822,Porbandar,802522,Porbandar (M + OG)
    24,GUJARAT,478,Porbandar ,3822,Porbandar,802522,Porbandar (M)
    24,GUJARAT,478,Porbandar ,3822,Porbandar,802523,Chhaya (M)
    24,GUJARAT,478,Porbandar ,3823,Ranavav,802524,Ranavav (M)
    24,GUJARAT,478,Porbandar ,3824,Kutiyana,802525,Kutiyana (M)
    24,GUJARAT,479,Junagadh,3825,Manavadar,802526,Bantwa (M)
    24,GUJARAT,479,Junagadh,3825,Manavadar,802527,Manavadar (M)
    24,GUJARAT,479,Junagadh,3826,Vanthali,802528,Vanthali (M)
    24,GUJARAT,479,Junagadh,3827,Junagadh,802529,Junagadh (M Corp.)
    24,GUJARAT,479,Junagadh,3829,Visavadar,802530,Visavadar (M)
    24,GUJARAT,479,Junagadh,3831,Keshod,802531,Keshod (M)
    24,GUJARAT,479,Junagadh,3832,Mangrol,802532,Mangrol (M + OG)
    24,GUJARAT,479,Junagadh,3832,Mangrol,802532,Mangrol (M)
    24,GUJARAT,479,Junagadh,3833,Malia,802533,Chorvad (M)
    24,GUJARAT,479,Junagadh,3834,Talala,802534,Talala (M)
    24,GUJARAT,479,Junagadh,3835,Patan-Veraval,802535,Veraval (M + OG)
    24,GUJARAT,479,Junagadh,3835,Patan-Veraval,802535,Veraval (M)
    24,GUJARAT,479,Junagadh,3836,Sutrapada,802536,Sutrapada (M)
    24,GUJARAT,479,Junagadh,3837,Kodinar,802537,Kodinar (M)
    24,GUJARAT,479,Junagadh,3838,Una,802538,Una (M)
    24,GUJARAT,480,Amreli,3840,Babra,802539,Babra (M)
    24,GUJARAT,480,Amreli,3841,Lathi,802540,Lathi (M)
    24,GUJARAT,480,Amreli,3841,Lathi,802541,Damnagar (M)
    24,GUJARAT,480,Amreli,3843,Amreli,802542,Amreli (M + OG)
    24,GUJARAT,480,Amreli,3843,Amreli,802542,Amreli (M)
    24,GUJARAT,480,Amreli,3844,Bagasara,802543,Bagasara (M)
    24,GUJARAT,480,Amreli,3845,Dhari,802544,Chalala (M)
    24,GUJARAT,480,Amreli,3846,Savar Kundla,802545,Savarkundla (M)
    24,GUJARAT,480,Amreli,3848,Jafrabad,802546,Jafrabad (M)
    24,GUJARAT,480,Amreli,3849,Rajula,802547,Rajula (M)
    24,GUJARAT,481,Bhavnagar,3850,Botad,802548,Botad (M)
    24,GUJARAT,481,Bhavnagar,3851,Vallabhipur,802549,Vallabhipur (M)
    24,GUJARAT,481,Bhavnagar,3852,Gadhada,802550,Gadhada (M)
    24,GUJARAT,481,Bhavnagar,3854,Bhavnagar,802551,Bhavnagar (M Corp. + OG)
    24,GUJARAT,481,Bhavnagar,3854,Bhavnagar,802551,Bhavnagar (M Corp.)
    24,GUJARAT,481,Bhavnagar,3856,Sihor,802552,Sihor (M)
    24,GUJARAT,481,Bhavnagar,3857,Gariadhar,802553,Gariadhar (M)
    24,GUJARAT,481,Bhavnagar,3858,Palitana,802554,Palitana (M)
    24,GUJARAT,481,Bhavnagar,3859,Talaja,802555,Talaja (M)
    24,GUJARAT,481,Bhavnagar,3859,Talaja,802556,Alang-Sosiya (INA)
    24,GUJARAT,481,Bhavnagar,3860,Mahuva,802557,Mahuva (M + OG)
    24,GUJARAT,481,Bhavnagar,3860,Mahuva,802557,Mahuva (M)
    24,GUJARAT,482,Anand  ,3862,Sojitra,802558,Sojitra (M)
    24,GUJARAT,482,Anand  ,3863,Umreth,802559,Umreth (M)
    24,GUJARAT,482,Anand  ,3864,Anand,802560,Boriavi (M)
    24,GUJARAT,482,Anand  ,3864,Anand,802561,Ode (M)
    24,GUJARAT,482,Anand  ,3864,Anand,802562,Anand (M + OG)
    24,GUJARAT,482,Anand  ,3864,Anand,802562,Anand (M)
    24,GUJARAT,482,Anand  ,3864,Anand,802563,Vallabh Vidyanagar (M)
    24,GUJARAT,482,Anand  ,3864,Anand,802564,Karamsad (M)
    24,GUJARAT,482,Anand  ,3864,Anand,802565,Vithal Udyognagar (INA)
    24,GUJARAT,482,Anand  ,3865,Petlad,802566,Petlad (M)
    24,GUJARAT,482,Anand  ,3866,Khambhat,802567,Khambhat (M + OG)
    24,GUJARAT,482,Anand  ,3866,Khambhat,802567,Khambhat (M)
    24,GUJARAT,482,Anand  ,3867,Borsad,802568,Borsad (M)
    24,GUJARAT,482,Anand  ,3867,Borsad,802569,Vasna Borsad (INA)
    24,GUJARAT,482,Anand  ,3868,Anklav,802570,Anklav (M)
    24,GUJARAT,483,Kheda,3869,Kapadvanj,802571,Kapadvanj (M)
    24,GUJARAT,483,Kheda,3871,Balasinor,802572,Balasinor (M)
    24,GUJARAT,483,Kheda,3872,Kathlal,802573,Kathlal (M)
    24,GUJARAT,483,Kheda,3873,Mehmedabad,802574,Mehmedabad (M)
    24,GUJARAT,483,Kheda,3874,Kheda,802575,Kheda (M)
    24,GUJARAT,483,Kheda,3876,Nadiad,802576,Nadiad (M + OG)
    24,GUJARAT,483,Kheda,3876,Nadiad,802576,Nadiad (M)
    24,GUJARAT,483,Kheda,3876,Nadiad,802577,Chaklasi (M)
    24,GUJARAT,483,Kheda,3876,Nadiad,802578,Kanjari (M)
    24,GUJARAT,483,Kheda,3877,Mahudha,802579,Mahudha (M)
    24,GUJARAT,483,Kheda,3878,Thasra,802580,Thasra (M)
    24,GUJARAT,483,Kheda,3878,Thasra,802581,Dakor (M + OG)
    24,GUJARAT,483,Kheda,3878,Thasra,802581,Dakor (M)
    24,GUJARAT,484,Panch Mahals,3881,Santrampur,802582,Santrampur (M)
    24,GUJARAT,484,Panch Mahals,3882,Lunawada,802583,Lunawada (M)
    24,GUJARAT,484,Panch Mahals,3883,Shehera,802584,Shehera (M)
    24,GUJARAT,484,Panch Mahals,3885,Godhra,802585,Godhra (M)
    24,GUJARAT,484,Panch Mahals,3886,Kalol,802586,Kalol (M + OG)
    24,GUJARAT,484,Panch Mahals,3886,Kalol,802586,Kalol (M)
    24,GUJARAT,484,Panch Mahals,3886,Kalol,802587,Kalol (INA)
    24,GUJARAT,484,Panch Mahals,3888,Halol,802588,Halol (M + OG)
    24,GUJARAT,484,Panch Mahals,3888,Halol,802588,Halol (M)
    24,GUJARAT,485,Dohad  ,3891,Jhalod,802589,Jhalod (M)
    24,GUJARAT,485,Dohad  ,3893,Dohad,802590,Dohad (M + OG)
    24,GUJARAT,485,Dohad  ,3893,Dohad,802590,Dohad (M)
    24,GUJARAT,485,Dohad  ,3895,Devgadbaria,802591,Devgadbaria (M)
    24,GUJARAT,486,Vadodara,3897,Savli,802592,Savli (M)
    24,GUJARAT,486,Vadodara,3898,Vadodara,802593,Nandesari (INA)
    24,GUJARAT,486,Vadodara,3898,Vadodara,802594,Petro-Chemical Complex (INA)
    24,GUJARAT,486,Vadodara,3898,Vadodara,802595,GSFC Complex (INA)
    24,GUJARAT,486,Vadodara,3898,Vadodara,802596,Vadodara (M Corp. + OG)
    24,GUJARAT,486,Vadodara,3898,Vadodara,802596,Vadodara (M Corp.)
    24,GUJARAT,486,Vadodara,3898,Vadodara,802597,Por-Ramangamdi (INA)
    24,GUJARAT,486,Vadodara,3899,Vaghodia,802598,Vaghodia (INA)
    24,GUJARAT,486,Vadodara,3901,Chhota Udaipur,802599,Chhota Udaipur (M)
    24,GUJARAT,486,Vadodara,3905,Dabhoi,802600,Dabhoi (M)
    24,GUJARAT,486,Vadodara,3906,Padra,802601,Padra (M + OG)
    24,GUJARAT,486,Vadodara,3906,Padra,802601,Padra (M)
    24,GUJARAT,486,Vadodara,3907,Karjan,802602,Karjan (M)
    24,GUJARAT,487,Narmada,3910,Nandod,802603,Rajpipla (M)
    24,GUJARAT,488,Bharuch,3913,Jambusar,802604,Jambusar (M)
    24,GUJARAT,488,Bharuch,3914,Amod,802605,Amod (M)
    24,GUJARAT,488,Bharuch,3916,Bharuch,802606,Bharuch (INA)
    24,GUJARAT,488,Bharuch,3916,Bharuch,802607,Bharuch (M)
    24,GUJARAT,488,Bharuch,3918,Anklesvar,802608,Anklesvar (M + OG)
    24,GUJARAT,488,Bharuch,3918,Anklesvar,802608,Anklesvar (M)
    24,GUJARAT,488,Bharuch,3918,Anklesvar,802609,Anklesvar (INA)
    24,GUJARAT,488,Bharuch,3918,Anklesvar,802610,Panoli (INA)
    24,GUJARAT,488,Bharuch,3920,Valia,802611,Valia - Jhagadia (GNFC Scooter Project Area) (INA)
    24,GUJARAT,488,Bharuch,3920,Valia,802612,Valia (Naldhari) (INA)
    24,GUJARAT,489,The Dangs,3921,The Dangs,802613,Saputara (NA)
    24,GUJARAT,490,Navsari  ,3922,Navsari,802614,Navsari (M + OG)
    24,GUJARAT,490,Navsari  ,3922,Navsari,802614,Navsari (M)
    24,GUJARAT,490,Navsari  ,3923,Jalalpore,802615,Vijalpor (M)
    24,GUJARAT,490,Navsari  ,3924,Gandevi,802616,Gandevi (M)
    24,GUJARAT,490,Navsari  ,3924,Gandevi,802617,Bilimora (M)
    24,GUJARAT,491,Valsad,3927,Valsad,802618,Valsad (M + OG)
    24,GUJARAT,491,Valsad,3927,Valsad,802618,Valsad (M)
    24,GUJARAT,491,Valsad,3927,Valsad,802619,Valsad (INA)
    24,GUJARAT,491,Valsad,3928,Dharampur,802620,Dharampur (M)
    24,GUJARAT,491,Valsad,3929,Pardi,802621,Pardi (M)
    24,GUJARAT,491,Valsad,3929,Pardi,802622,Vapi (M)
    24,GUJARAT,491,Valsad,3929,Pardi,802623,Vapi (INA)
    24,GUJARAT,491,Valsad,3931,Umbergaon,802624,Sarigam (INA)
    24,GUJARAT,491,Valsad,3931,Umbergaon,802625,Umbergaon (M)
    24,GUJARAT,491,Valsad,3931,Umbergaon,802626,Umbergaon (INA)
    24,GUJARAT,492,Surat,3933,Mangrol,802627,Tarsadi (M)
    24,GUJARAT,492,Surat,3935,Mandvi,802628,Mandvi (M)
    24,GUJARAT,492,Surat,3937,Surat City,802629,Surat (M Corp. + OG) (Part)
    24,GUJARAT,492,Surat,3938,Chorasi,802629,Surat (M Corp. + OG) (Part)
    24,GUJARAT,492,Surat,3938,Chorasi,802630,Hajira (INA)
    24,GUJARAT,492,Surat,3938,Chorasi,802631,Magdalla (INA)
    24,GUJARAT,492,Surat,3938,Chorasi,802632,Sachin (INA)
    24,GUJARAT,492,Surat,3938,Chorasi,802633,Kansad (M)
    24,GUJARAT,492,Surat,3940,Bardoli,802634,Bardoli (M)
    24,GUJARAT,493,Tapi,3944,Songadh,802635,Songadh (M)
    24,GUJARAT,493,Tapi,3945,Vyara,802636,Vyara (M)
