version: '3.4'
services:
  jmeterclidemo:
    image: amit2711/jmeterperformanceautomation:latest
    environment:
        TokenKey: ${TokenKey}
        DBPassword: ${DBPassword}
    ports:
      - "5001:80"
      - "5000:443"
   
  mssql-service:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    entrypoint: "/bin/bash /app/script/entrypoint.sh"
    environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: ${DBPassword}
        MSSQL_PID: Express
    ports:
        - "1436:1433"
    volumes:
        - ./sql-script:/app/script
    depends_on:
        - jmeterclidemo

  awscli:
     image: amazon/aws-cli:latest
     environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
     entrypoint:  /app/aws-script/entrypoint.sh
     volumes:
      - ./aws-script:/app/aws-script
      - test-scripts:/app/test-scripts
      - results:/app/results
      - flag:/app/flag

  jmeter:
    image: justb4/jmeter:latest
    volumes: 
    - test-scripts:/jmeter/test-scripts
    - results:/jmeter/results
    - flag:/jmeter/flag
    entrypoint: "/bin/bash /jmeter/test-scripts/entrypoint.sh"
    depends_on: 
    - jmeterclidemo
    - mssql-service
    - awscli

volumes:
  test-scripts:
  results:
  flag: